### ISSUE TITLE
Подготовить данные для задачи STS

### ISSUE THREAD

**Issue by tedey-01** [tedey-01/UDK#2]
- [x] Собрать данные 
- [x] Подготовить данные 
- [x] Создать датасет для трансформера

**Comment by tedey-01** [comment]
@Elkhn По хорошему, PR с кодом парсеров должен был быть привязан к этой задаче.  В этой же задаче можно синхронизироваться по воспроизводимости кода.

**Comment by Elkhn** [comment]
@tedey-01 Данные норм парсятся 2016-2022 год в итоге 669 статей (на т.м.). За минуту все файлы сохраняются в csv весом ~30мб

**Comment by tedey-01** [comment]
@Elkhn Сейчас в мастере код актуальный ?

**Comment by Elkhn** [comment]
@tedey-01 Да, корректировок других не делал

**Comment by tedey-01** [comment]
Ок, закрываю задачу
